apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jraav0m8z-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jraav0m8z-dotnet-basic-gitops